openapi: "3.1.0"
info:
  title: LPA Store
  version: "1.0"
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://lpa-store.api.opg.service.justice.gov.uk
    description: Production
  - url: https://preproduction.lpa-store.api.opg.service.justice.gov.uk
    description: Preproduction
  - url: https://development.lpa-store.api.opg.service.justice.gov.uk
    description: Development
security:
  - {}
x-json-schema-faker:
  alwaysFakeOptionals: false
  optionalsProbability: 0.5
paths:
  /lpas:
    post:
      operationId: getList
      summary: Retrieve multiple LPAs
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetList"
      responses:
        "200":
          description: Cases retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetListResponse"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
      x-amazon-apigateway-auth:
        type: "AWS_IAM"
      x-amazon-apigateway-integration:
        uri: ${lambda_getlist_invoke_arn}
        httpMethod: "POST"
        type: "aws_proxy"
        contentHandling: "CONVERT_TO_TEXT"
  /lpas/{uid}:
    parameters:
      - name: uid
        in: path
        required: true
        description: The UID of the case
        schema:
          type: string
          pattern: "M-([A-Z0-9]{4})-([A-Z0-9]{4})-([A-Z0-9]{4})"
          example: M-789Q-P4DF-4UX3
    put:
      operationId: putLpa
      summary: Store an LPA
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DonorDetails"
      responses:
        "201":
          description: Case created
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
      x-amazon-apigateway-auth:
        type: "AWS_IAM"
      x-amazon-apigateway-integration:
        uri: ${lambda_create_invoke_arn}
        httpMethod: "POST"
        type: "aws_proxy"
        contentHandling: "CONVERT_TO_TEXT"
    get:
      operationId: getLpa
      summary: Retrieve an LPA
      responses:
        "200":
          description: Case found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Lpa"
              examples:
                lpa0138:
                  value:
                    "lpaType": "personal-welfare"
                    "channel": "online"
                    "donor":
                      "uid": "eda719db-8880-4dda-8c5d-bb9ea12c236f"
                      "firstNames": "Feeg"
                      "lastName": "Bundlaaaa"
                      "address":
                        "line1": "74 Cloob Close"
                        "town": "Mahhhhhhhhhh"
                        "country": "GB"
                      "dateOfBirth": "1970-01-24"
                      "email": "nobody@not.a.real.domain"
                      "contactLanguagePreference": "en"
                    "attorneys": [{"uid": "9ac5cb7c-fc75-40c7-8e53-059f36dbbe3d", "firstNames": "Herman", "lastName": "Seakrest", "address": {"line1": "81 NighOnTimeWeBuiltIt Street", "town": "Mahhhhhhhhhh", "country": "GB"}, "dateOfBirth": "1982-07-24", "status": "active", "channel": "paper"}]
                    "trustCorporations": [{"uid": "1d95993a-ffbb-484c-b2fe-f4cca51801da", "name": "Trust us Corp.", "companyNumber": "666123321", "address": {"line1": "103 Line 1", "town": "Town", "country": "GB"}, "status": "active", "channel": "paper"}]
                    "certificateProvider":
                      "uid": "6808960d-12cf-47c5-a2bc-3177deb8599c"
                      "firstNames": "Vone"
                      "lastName": "Spust"
                      "address":
                        "line1": "122111 Zonnington Way"
                        "town": "Mahhhhhhhhhh"
                        "country": "GB"
                      "channel": "online"
                      "email": "a@example.com"
                      "phone": "070009000"
                    "lifeSustainingTreatmentOption": "option-a"
                    "signedAt": "2024-01-10T23:00:00Z"
                    "certificateProviderNotRelatedConfirmedAt": "2024-01-11T22:00:00Z"
                    "howAttorneysMakeDecisions": "jointly"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "404":
          description: Case not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
      x-amazon-apigateway-auth:
        type: "AWS_IAM"
      x-amazon-apigateway-integration:
        uri: ${lambda_get_invoke_arn}
        httpMethod: "POST"
        type: "aws_proxy"
        contentHandling: "CONVERT_TO_TEXT"
  /lpas/{uid}/updates:
    parameters:
      - name: uid
        in: path
        required: true
        description: The UID of the case
        schema:
          type: string
          pattern: "M-([A-Z0-9]{4})-([A-Z0-9]{4})-([A-Z0-9]{4})"
          example: M-789Q-P4DF-4UX3
    post:
      operationId: createUpdate
      summary: Update an LPA
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Update"
      responses:
        "201":
          description: Update created
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
      x-amazon-apigateway-auth:
        type: "AWS_IAM"
      x-amazon-apigateway-integration:
        uri: ${lambda_update_invoke_arn}
        httpMethod: "POST"
        type: "aws_proxy"
        contentHandling: "CONVERT_TO_TEXT"
  /health-check:
    get:
      operationId: healthCheck
      summary: Health check endpoint for external services to consume
      responses:
        "200":
          description: Healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                additionalProperties: false
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Unhealthy
                additionalProperties: false
      x-amazon-apigateway-auth:
        type: "NONE"
      x-amazon-apigateway-integration:
        type: "mock"
        responses:
          default:
            statusCode: 200
            responseTemplates:
              application/json: '{"status":"ok", "statusCode":200}'
        requestTemplates:
          application/json: '{"statusCode": 200}'
        passthroughBehavior: "when_no_templates"
components:
  schemas:
    AbstractError:
      type: object
      required:
        - code
        - detail
      properties:
        code:
          type: string
        detail:
          type: string
    BadRequestError:
      allOf:
        - $ref: "#/components/schemas/AbstractError"
        - type: object
          properties:
            code:
              enum: ["INVALID_REQUEST"]
            errors:
              type: array
              items:
                type: object
                required:
                  - source
                  - detail
                properties:
                  source:
                    type: string
                    format: jsonpointer
                  detail:
                    type: string
              example:
                - source: "/uid"
                  detail: "invalid uid format"
    NotFoundError:
      allOf:
        - $ref: "#/components/schemas/AbstractError"
        - type: object
          properties:
            code:
              enum: ["NOT_FOUND"]
    GetList:
      type: object
      required:
        - uids
      properties:
        uids:
          type: array
          items:
            type: string
            pattern: M-([A-Z0-9]{4})-([A-Z0-9]{4})-([A-Z0-9]{4})
            example: M-789Q-P4DF-4UX3
    GetListResponse:
      type: object
      required:
        - lpas
      properties:
        lpas:
          type: array
          items:
            $ref: "#/components/schemas/Lpa"
    Lpa:
      $ref: "../schemas/2024-10/lpa.json"
    DonorDetails:
      $ref: "../schemas/2024-10/donor-details.json"
    Update:
      type: object
      required:
        - type
        - changes
      properties:
        type:
          enum:
            - CERTIFICATE_PROVIDER_SIGN
            - ATTORNEY_SIGN
            - TRUST_CORPORATION_SIGN
            - PERFECT
            - REGISTER
            - CERTIFICATE_PROVIDER_OPT_OUT
        changes:
          type: array
          items:
            type: object
            required:
              - key
              - old
              - new
            properties:
              key:
                type: string
              old:
                oneOf:
                  - type: string
                  - type: number
                  - type: boolean
                  - type: "null"
              new:
                oneOf:
                  - type: string
                  - type: number
                  - type: boolean
                  - type: "null"
