name: Psalm Static analysis - Service

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
    # paths:
    # # only run when service-front is changed
    #   - 'service-front/**'

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    defaults:
      run:
        # shell: bash
        working-directory: service-front/app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check what's here
        run: ls -al

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: vimeo/psalm

      - name: Composer install
        run: composer install

      - name: Run psalm
        run: psalm


      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif

      # - name: Psalm
      #   env:
      #     GITHUB_WORKSPACE: /github/workspace/opg-use-an-lpa/service-front/app
      #     RUNNER_WORKSPACE: /github/workspace/opg-use-an-lpa/service-front/app
      #   uses: docker://vimeo/psalm-github-actions
      #   with:
      #     composer_require_dev: false
      #     composer_ignore_platform_reqs: false
      #     security_analysis: true
      #     report_file: results.sarif
      # - name: Upload Security Analysis results to GitHub
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: results.sarif
